# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmU5NjdmOTZlNzUzYmI2YjEyZTg0ZTZhYzQwMTQyNjdlMWE2MTA5M2FlYWNlMDFjYzMzZWFmMGMwNmE5N2EyNTllOTNhYWQ3YWI1MmVjOGZmMzUxZTU4MjZmMDA1Mjg0NGZkZWVlMGQ4Y2VhMTUxYWVjYjczYzZjMzgwYTUxZDg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
